import React from 'react';

const COUNTRY_CODES = [
  { value: '', label: 'Select country', disabled: true },
  { value: '+91', label: 'India +91' },
  { value: '+1', label: 'USA +1' },
  { value: '+44', label: 'UK +44' },
  { value: '+61', label: 'Australia +61' },
  { value: '+971', label: 'UAE +971' },
];

export default function CompanyDetails({ formData, onChange }) {
  const handlePhoneInput = (e) => {
    const digits = e.target.value.replace(/\D/g, '').slice(0, 10);
    onChange('phone', digits);
  };

  const handlePhonePaste = (e) => {
    e.preventDefault();
    const paste = (e.clipboardData || window.clipboardData).getData('text');
    const digits = paste.replace(/\D/g, '').slice(0, 10);
    onChange('phone', digits);
  };

  const handlePhoneKeyDown = (e) => {
    // Allow: backspace, delete, tab, escape, enter, arrows
    const allowed = ['Backspace', 'Delete', 'Tab', 'Escape', 'Enter', 'ArrowLeft', 'ArrowRight', 'Home', 'End'];
    if (allowed.includes(e.key)) return;
    // Allow Ctrl+A, Ctrl+C, Ctrl+V, Ctrl+X
    if ((e.ctrlKey || e.metaKey) && ['a', 'c', 'v', 'x'].includes(e.key.toLowerCase())) return;
    // Block non-digit
    if (!/^\d$/.test(e.key)) {
      e.preventDefault();
      return;
    }
    // Block if already 10 digits (unless selecting text)
    const currentDigits = formData.phone.replace(/\D/g, '');
    const selectionLength = e.target.selectionEnd - e.target.selectionStart;
    if (currentDigits.length - selectionLength >= 10) {
      e.preventDefault();
    }
  };

  return (
    <div className="card card-animate">
      <h2>
        <span className="card-icon">🏢</span>
        Company Details
      </h2>

      <div className="row">
        <label htmlFor="company">Company Name</label>
        <input
          type="text"
          id="company"
          value={formData.company}
          onChange={(e) => onChange('company', e.target.value)}
        />
      </div>

      <div className="row phone-row">
        <label htmlFor="phone">Phone</label>
        <div className="phone-group">
          <select
            id="phoneCountry"
            value={formData.phoneCountry}
            onChange={(e) => onChange('phoneCountry', e.target.value)}
          >
            {COUNTRY_CODES.map((c) => (
              <option key={c.value} value={c.value} disabled={c.disabled}>
                {c.label}
              </option>
            ))}
          </select>
          <input
            type="tel"
            id="phone"
            value={formData.phone}
            maxLength={10}
            inputMode="numeric"
            pattern="[0-9]*"
            placeholder="10 digits only"
            autoComplete="tel"
            onChange={handlePhoneInput}
            onPaste={handlePhonePaste}
            onKeyDown={handlePhoneKeyDown}
          />
        </div>
      </div>

      <div className="row">
        <label htmlFor="email">Email</label>
        <input
          type="email"
          id="email"
          value={formData.email}
          placeholder="email@example.com"
          onChange={(e) => onChange('email', e.target.value)}
        />
      </div>

      <div className="row">
        <label htmlFor="generatedBy">Report Generated By</label>
        <input
          type="text"
          id="generatedBy"
          value={formData.generatedBy}
          placeholder="Your name"
          onChange={(e) => onChange('generatedBy', e.target.value)}
        />
      </div>
    </div>
  );
}
