import { formatNumber } from './formatNumber';
import { calculateFinancials } from './calculations';

/**
 * Build a plain-text financial report for sharing.
 * @param {Object} formData - All form field values
 * @returns {string} Formatted report text
 */
export function buildReportText(formData) {
  const {
    company = 'N/A',
    phoneCountry = '',
    phone = '',
    email = 'N/A',
    generatedBy = 'N/A',
    client = 'N/A',
    currency = '₹',
    investment = 0,
    months = 'N/A',
    profitAmount = 0,
    profitPercent = 0,
    outstandingAmount = 0,
    outstandingPercent = 0,
  } = formData;

  const phoneDisplay = phone ? `${phoneCountry} ${phone}` : 'N/A';

  const results = calculateFinancials({
    investment: Number(investment) || 0,
    profitAmount: Number(profitAmount) || 0,
    profitPercent: Number(profitPercent) || 0,
    outstandingAmount: Number(outstandingAmount) || 0,
    outstandingPercent: Number(outstandingPercent) || 0,
  });

  return `Financial Report

Company: ${company}
Phone: ${phoneDisplay}
Email: ${email || 'N/A'}
Generated By: ${generatedBy || 'N/A'}
Client Name: ${client || 'N/A'}
Currency: ${currency}
Investment Amount: ${currency}${formatNumber(Number(investment) || 0)}
Maturity Period: ${months}
Profit Withdrawal: ${currency}${formatNumber(Number(profitAmount) || 0)}
Profit %: ${formatNumber(Number(profitPercent) || 0)}%
Outstanding Withdrawal: ${currency}${formatNumber(Number(outstandingAmount) || 0)}
Outstanding %: ${formatNumber(Number(outstandingPercent) || 0)}%

Maturity Amount: ${currency}${formatNumber(results.maturityAmount)}
Profit Value: ${currency}${formatNumber(results.profitValue)}
Outstanding Value: ${currency}${formatNumber(results.outstandingValue)}
Total Value: ${currency}${formatNumber(results.totalValue)}
Leftover Value: ${currency}${formatNumber(results.leftoverValue)}
Transfer Value: ${currency}${formatNumber(results.transferValue)}
Monthly Profit: ${currency}${formatNumber(results.monthlyProfit)}
`;
}
